/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CP1.c
**     Project   : Project4
**     Processor : MC9S12XS256MAL
**     Component : Init_COP
**     Version   : Component 01.038, Driver 01.05, CPU db: 3.00.020
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2019-07-11, ¿ÀÈÄ 3:23
**     Abstract  :
**          This file implements the Computer Operating Properly (COP)
**          module initialization according to the Peripheral 
**          Initialization Component settings.
**          The (COP) module contains a free-running counter that generates
**          a reset if allowed to overflow. The COP module
**          helps software recover from runaway code. Prevent a COP reset by 
**          clearing the COP counter periodically.

**     Settings  :
**          Component name                                 : CP1
**          Device                                         : COPControl
**          Settings 
**            Clock setting 
**              Time-out period prescaler                  : 7
**              Time-out period                            : 1048.576 ms
**          Initialization 
**            Call Init method                             : yes
**     Contents  :
**         Init - void CP1_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE CP1. */

#include "CP1.h"
//


/*
** ===================================================================
**     Method      :  CP1_Init (component Init_COP)
**
**     Description :
**         This method initializes registers of the COP module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details."
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void CP1_Init(void)
{
  /* CLKSEL: COPWAI=0 */
  clrReg8Bits(CLKSEL, 0x01U);           
  /* PLLCTL: PCE=0 */
  clrReg8Bits(PLLCTL, 0x02U);           
}

/* END CP1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
